version: "3.7"
services:
  server:
    build: .
    image: macy-search-server
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - ELASTIC_HOST=elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200
    #   - 9300:9300
    environment:
      - discovery.type=single-node

volumes:
  esdata:
    driver: local
